name: Build Docker

on:
  push:
    branches: [main, master]
    paths:
      - Dockerfile
      - '**/Dockerfile'
      - .github/workflows/build-docker.yml
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

concurrency:
  group: build-docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository }}:ci-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

